file = open('output.txt','w')
writing_file = file.write('Hello, Python!')
file.close()

file = open('output.txt','r')
read_file = file.read()
print("Enter text to write to the file:",read_file)
print("Data successfully written to my_file.txt.")
file.close()

file = open('output.txt','a')
appending_file = file.write('\nLearning file handling in Python.')
print("Enter additional text to append: Learning file handling in Python.")
print("Data successfully appended.")
file.close()
file = open('output.txt','r')
read_file = file.read()
print("Final content of output.txt:")
print(read_file)
file.close()
